Update seeds, regen docs, merge 1.4.1 changes
fivetran/dbt_fivetran_log pull request #109
Opened 2024-01-04 11:15 UTC by fivetran-avinash

## PR Overview
**This PR will address the following Issue/Feature:**

**This PR will result in the following new package version:**

**Please provide the finalized CHANGELOG entry which details the relevant changes included in this PR:**

## PR Checklist
### Basic Validation
Please acknowledge that you have successfully performed the following commands locally:
- [ ] dbt run –full-refresh && dbt test
- [ ] dbt run (if incremental models are present) && dbt test

Before marking this PR as "ready for review" the following have been applied:
- [ ] The appropriate issue has been linked, tagged, and properly assigned
- [ ] All necessary documentation and version upgrades have been applied
- [ ] docs were regenerated (unless this PR does not include any code or yml updates)
- [ ] BuildKite integration tests are passing
- [ ] Detailed validation steps have been provided below

### Detailed Validation
Please share any and all of your validation steps:

### If you had to summarize this PR in an emoji, which would it be?
 
:dancer:

2024-01-05 21:30 UTC, fivetran-joemarkiewicz requested changes
@fivetran-avinash thanks for working through this! This is looking good, but I have a few comments and suggestions below. Let me know if you have any questions - we can sync on the SQL Server one in more detail next week, but you should be able to start building out the bones of a conditional knowing SQL Server likely doesn't support the `limit` function.

2024-01-08 19:34 UTC, fivetran-avinash commented on models/staging/stg_fivetran_platform__credits_used.sql
> +limit 0
updated with offset/fetch as it was the most readable, and runs through the process of limit 0 in one loop rather than two separate ones.

2024-01-08 19:35 UTC, fivetran-avinash commented on README.md
> +    fivetran_platform__usage_pricing: false #this will disable only the usage cost logic
@fivetran-joemarkiewicz Agreed, removed README changes and updated DECISIONLOG.

2024-01-08 19:35 UTC, fivetran-avinash commented on CHANGELOG.md
> +- Adjusted staging models `stg_fivetran_platform__credits_used` and `stg_fivetran_platform__usage_cost` to return empty tables if the respective `fivetran_platform__credits_pricing` and the `fivetran
Updated.

2024-01-08 19:35 UTC, fivetran-avinash commented on CHANGELOG.md
> +- Added additional scripts to `run_models.sh` for the package with the variables `fivetran_platform__credits_pricing` set to false and `fivetran_platform__usage_pricing` set to true to recreate the e
Updated.

2024-01-08 19:35 UTC, fivetran-avinash commented on CHANGELOG.md
> +- Updated seed files to ensure downstream models properly populate into `fivetran_platform__usage_mar_destination_history` for validating this PR.
Updated.

2024-01-08 20:37 UTC, fivetran-avinash commented
@fivetran-joemarkiewicz Changes applied and ready for re-review.

2024-01-08 20:53 UTC, fivetran-joemarkiewicz commented on models/staging/stg_fivetran_platform__credits_used.sql
> +limit 0
This is great, thanks @fivetran-avinash! Upon first glance this looks good, but we will be able to actually test once the sqlserver warehouse is back up and running.

2024-01-08 20:55 UTC, fivetran-joemarkiewicz approved these changes
@fivetran-avinash these changes look great to me, thanks for applying them! I have approved the PR as your changes look good, but I would like to hold off merging and releasing until we can get the sqlserver warehouse back up and running to fully test. 

Once Buildkite is passing on the soon to be recreated sqlserver warehouse, we can initialize the release review process.

2024-01-09 21:17 UTC, fivetran-joemarkiewicz commented on integration_tests/ci/sample.profiles.yml
> +      schema: fivetran_platform_integration_testss
```suggestion
      schema: fivetran_platform_integration_tests
```

2024-01-10 18:37 UTC, merged