Update README.md
fivetran/dbt_fivetran_log pull request #125
Opened 2024-05-10 10:50 UTC by jlmendgom5TRAN

Links: https://fivetran.height.app/T-680085

Fixes a 404 identified here:

![404ide](https://github.com/fivetran/dbt_fivetran_log/assets/86319365/662932bf-7f05-4a5e-b1ff-5f29373a5e32)

2024-05-10 18:26 UTC, fivetran-dejantucakov requested changes
@jlmendgom5TRAN Please see comments and suggestions

2024-05-10 18:26 UTC, fivetran-dejantucakov commented on README.md
> +- Produces staging models in the format described by [this ERD](https://fivetran.com/docs/logs/fivetran-platform#schemainformation) which clean, test, and prepare your Fivetran data from our free [Fi
```suggestion
- Produces staging models in the format described by [this ERD](https://fivetran.com/docs/logs/fivetran-platform#schemainformation) which clean, test, and prepare your Fivetran data from our free [Fivetran Platform connector](https://fivetran.com/docs/logs/fivetran-platform) and generates analysis ready end models.
```
DBT docs work differently, so we need full URL paths

2024-05-10 18:26 UTC, fivetran-dejantucakov commented on README.md
>  - The above mentioned models enable you to better understand how you are spending money in Fivetran according to our [consumption-based pricing model](https://fivetran.com/docs/getting-started/consum
```suggestion
- The above mentioned models enable you to better understand how you are spending money in Fivetran according to our [consumption-based pricing model](https://fivetran.com/docs/usage-based-pricing) as well as providing details about the performance and status of your Fivetran connectors. This is achieved by:
```
One less redirect.

2024-05-17 13:42 UTC, fivetran-joemarkiewicz approved these changes
LGTM

2024-05-17 13:43 UTC, merged