Feature/add transformation runs
fivetran/dbt_fivetran_log pull request #141
Opened 2024-12-17 18:47 UTC by fivetran-reneeli

**Please provide your name and company**

**Link the issue/feature request which this PR is meant to address**

**Detail what changes this PR introduces and how this addresses the issue/feature request linked above.**

**How did you validate the changes introduced within this PR?**

**Which warehouse did you use to develop these changes?**

**Did you update the CHANGELOG?**

- [ ] Yes

**Did you update the dbt_project.yml files with the version upgrade (please leverage standard semantic versioning)? (In both your main project and integration_tests)**

- [ ] Yes

**Typically there are additional maintenance changes required before this will be ready for an upcoming release. Are you comfortable with the Fivetran team making a few commits directly to your branch?**

- [ ] Yes
- [ ] No

**If you had to summarize this PR in an emoji, which would it be?**
 
:dancer:

**Feedback**

We are so excited you decided to contribute to the Fivetran community dbt package! We continue to work to improve the packages and would greatly appreciate your [feedback](https://www.surveymonkey.com/r/DQ7K7WW) on our existing dbt packages or what you'd like to see next.

**PR Template** 
- [Community Pull Request Template](?expand=1&template=pull_request_template.md) (default)

- [Maintainer Pull Request Template](?expand=1&template=maintainer_pull_request_template.md) (to be used by maintainers)

2024-12-30 21:31 UTC, fivetran-jamie requested changes
This looks pretty good!! Made some minor suggestions and I have a couple of larger questions/requests:

1. Can we confirm with eng whether or not customers who do not use transformations at all will have the `transformation_runs` table in their schemas? Wondering if we need to include a variable
2. Can you move the Hex validations to a new `integrity` data validation test here?

2025-01-03 23:36 UTC, fivetran-reneeli commented on models/staging/stg_fivetran_platform__transformation_runs.sql
> +        }}
thanks for catching!

2025-01-03 23:41 UTC, fivetran-reneeli commented on models/staging/stg_fivetran_platform__transformation_runs.sql
> +    {{ dbt.date_trunc('month', 'measured_date') }} as measured_month
Initially I had tried just having it just in the final CTE, but there were issues hence I did it here. Let me try it again though

2025-01-04 00:07 UTC, fivetran-reneeli commented on models/fivetran_platform__usage_mar_destination_history.sql
> +        sum(model_runs) as total_model_runs
added this in! thanks!

2025-01-04 00:08 UTC, fivetran-reneeli commented on models/fivetran_platform__usage_mar_destination_history.sql
> +        cast(measured_month as date) as measured_month,
moved it!

2025-01-04 00:12 UTC, fivetran-reneeli commented on CHANGELOG.md
> +  - Added the following fields to the `fivetran_platform__usage_mar_destination_history` end model for each destination and month:
added

2025-01-04 00:12 UTC, fivetran-reneeli commented on CHANGELOG.md
> +  - Added a new staging `stg_fivetran_platform__transformation_runs` model. Additionally, a new tmp model `stg_fivetran_platform__transformation_runs_tmp` and `get_transformation_runs_columns()` macr
added in and checked that the indenting looks good

2025-01-04 00:18 UTC, fivetran-reneeli commented on models/staging/stg_fivetran_platform__transformation_runs.sql
> +    {{ dbt.date_trunc('month', 'measured_date') }} as measured_month
Oh yeah it's this error.
<img width="1024" alt="image" src="https://github.com/user-attachments/assets/185a7a70-cd49-464b-bb1b-f33a9e79e7cd" />

So it needs to go through the timestamp casting first otherwise it's not getting interpreted correctly.

2025-01-04 00:23 UTC, fivetran-reneeli commented on models/staging/stg_fivetran_platform.yml
> +    description: Table of all transformation runs that have been executed by Fivetran.
thank you for catching!!

2025-01-04 00:26 UTC, fivetran-reneeli commented on models/fivetran_platform__usage_mar_destination_history.sql
> +        on destination_mar.measured_month = cast(transformation_runs.measured_month as date)
good point. i noticed both are previously already cast as date. let me try to remove them both

2025-01-04 00:44 UTC, fivetran-reneeli commented
Thanks @fivetran-jamie for the review, ready for another look! I also made the new validation test comparing run counts. I also asked eng, that's a good point.

2025-01-10 21:57 UTC, fivetran-reneeli commented on models/staging/stg_fivetran_platform__transformation_runs.sql
Now that we're using the `does_table_exist` macro and have to create a conditional block to pass all null fields for when table does not exist, I believe it doesn't work with the tmp model so I removed that, and instead wrapped up everything in the staging model as shown. This follows what's done in the `stg_fivetran_platform__usage_cost` model

2025-01-10 22:01 UTC, fivetran-reneeli commented
Updates are addressing the fact that this `transformation_runs` table doesn't always exist in the customer schema. Therefore I used the `does_table_exist` macro to then pass to the `fivetran_platform_using_transformations` variable. Major updates: removed the config from the src.yml, removed documentation about configuring the variable, changed the logic in stg_fivetran_platform__transformation_runs, and removed the conditional logic downstream now that the staging model will be passed regardless, just as an empty table if the source doesn't exist.

2025-01-13 23:40 UTC, fivetran-jamie reviewed
runs great! some minor suggestions

2025-01-14 18:51 UTC, fivetran-reneeli commented on models/staging/src_fivetran_platform.yml
> +        description: Table of all transformation runs that have been executed by Fivetran.
good note!

2025-01-14 19:40 UTC, fivetran-reneeli commented on CHANGELOG.md
> +- *NOTE*: Not all customers will have the `transformation_runs` source table, particularly if they are not using Fivetran Transformations. Therefore, the `transformation_runs` table will only populat
yeah true. i added it in here and shuffled the order of the sections

2025-01-14 19:47 UTC, fivetran-reneeli commented on README.md
> +If you do not leverage Fivetran RBAC, then you will not have the `user` or `destination_membership` source tables. The `user` and `destination_membership` are enabled by default. Therefore in order t
added a section in the DECISIONLOG

2025-01-14 20:08 UTC, fivetran-reneeli commented on models/fivetran_platform__usage_mar_destination_history.sql
> +        on destination_mar.measured_month = usage.measured_month
yes no prob!

2025-01-15 22:16 UTC, fivetran-jamie reviewed
looking great, couple of minor doc-related comments

2025-01-15 22:16 UTC, fivetran-jamie commented on DECISIONLOG.md
> +Not all customers have the `transformation_runs` source table, particularly if they are not using Fivetran Transformations. Therefore, we leverage a new variable `fivetran_platform_using_transformati
```suggestion
Not all customers have the `transformation_runs` source table, particularly if they are not using Fivetran Transformations. Therefore, we leverage a new variable `fivetran_platform_using_transformations`, which automatically checks for the table. If it exists, the variable is set to True, which then persists the `transformation_runs` source table and related models and downstream fields. If the table doesn't exist, the staging `stg_fivetran_platform__transformation_runs` model will persist as an empty model and respective downstream fields will be null. 

In the case you have the `transformation_runs` source table but still wish to disable it to prevent it from being populated in the package, you may set `fivetran_platform_using_transformations` to False in your project.yml.
```

And can you add the variable yml configuration block, like what we have in the above section for `fivetran_platform__usage_pricing` and `fivetran_platform__credits_pricing`

2025-01-15 22:16 UTC, fivetran-jamie commented on CHANGELOG.md
> +## Documentation Updates
can you add the DECISIONLOG addition to this section and link to it

2025-01-15 22:16 UTC, fivetran-jamie commented on CHANGELOG.md
> +- We have added the `transformation_runs` source table. Note that not all customers have the `transformation_runs` source table, particularly if they are not using Fivetran Transformations. Therefore
Can you add a note somewhere in the CHANGELOG about being able to override this behavior by setting `fivetran_platform_using_transformations` to False, similar to what you have in the DECISIONLOG

2025-01-16 20:25 UTC, fivetran-reneeli commented on CHANGELOG.md
> +## Documentation Updates
done!

2025-01-16 20:25 UTC, fivetran-reneeli commented on CHANGELOG.md
> +- We have added the `transformation_runs` source table. Note that not all customers have the `transformation_runs` source table, particularly if they are not using Fivetran Transformations. Therefore
added

2025-01-17 21:12 UTC, fivetran-jamie approved these changes
LGTM!

2025-01-21 22:49 UTC, fivetran-joemarkiewicz requested changes
@fivetran-reneeli a few questions and change requests before approval.

2025-01-21 22:49 UTC, fivetran-joemarkiewicz commented on CHANGELOG.md
> +    - We have also added the `get_transformation_runs_columns()` macro to ensure all required columns are present.
Let's move this to an under the hood change since this isn't really applicable for users as a breaking schema change.

2025-01-21 22:49 UTC, fivetran-joemarkiewicz commented on CHANGELOG.md
> +- Added information about manually configuring the `fivetran_platform_using_transformations` variable in the [DECISION LOG.](https://github.com/fivetran/dbt_fivetran_log/blob/main/DECISIONLOG.md)## D
```suggestion
- Added information about manually configuring the `fivetran_platform_using_transformations` variable in the [DECISION LOG](https://github.com/fivetran/dbt_fivetran_log/blob/main/DECISIONLOG.md).
```

2025-01-21 22:49 UTC, fivetran-joemarkiewicz commented on models/fivetran_platform__usage_mar_destination_history.sql
> +        sum(case when free_type != 'PAID' then model_runs else 0 end) as free_model_runs,
We've seen cases in the past where the casing of strings in the Fivetran Platform data model could possibly change in the future. Can we make this more future proof and simple to a lower casing search?
```suggestion
        sum(case when lower(free_type) = 'paid' then model_runs else 0 end) as paid_model_runs,
        sum(case when lower(free_type) != 'paid' then model_runs else 0 end) as free_model_runs,
```

2025-01-21 22:49 UTC, fivetran-joemarkiewicz commented on models/staging/src_fivetran_platform.yml
> +        identifier: '{{ var("fivetran_log_transformation_runs_identifier", "transformation_runs") }}'
Small note - all other identifier variables have double quotes enclosing the bracket config and then single quotes for calling the variable. Let's use the same format as the other identifiers in this package to ensure consistency and that dbt doesn't behave any differently than expected across the board.
```suggestion
        identifier: "{{ var('fivetran_log_transformation_runs_identifier', 'transformation_runs') }}"
```

2025-01-21 22:49 UTC, fivetran-joemarkiewicz commented on models/staging/stg_fivetran_platform__transformation_runs.sql
> +    {% endif %}
Do we need to account for Redshift to limit 1 as we've recently uncovered with the union data practices?

cc: @fivetran-jamie

2025-01-21 22:49 UTC, fivetran-joemarkiewicz commented on CHANGELOG.md
> +  - If you would like to override these updates, you can also manually disable the `fivetran_platform_using_transformations` variable by setting it to False in your project.yml
This CHANGELOG entry is confusing or misleading. I read this and imagine that if I define `fivetran_platform_using_transformations: false` then these three mentioned fields will not be present in the end model. However, setting this to false will simply ensure all of the results are `null`.

Can you confirm the `null` behavior is what is expected? If so, we should rethink this. Why would someone want to manually set this variable as `false` if the fields will still be present, just empty?

2025-01-21 22:49 UTC, fivetran-joemarkiewicz commented on CHANGELOG.md
> +  - Added a new staging [`stg_fivetran_platform__transformation_runs`](https://fivetran.github.io/dbt_fivetran_log/#!/model/model.fivetran_log.stg_fivetran_platform__transformation_runs) model.
I feel we're adding more here than is necessary or useful to the customer and could potentially cause confusion to the end customer.

[Here](https://github.com/fivetran/dbt_fivetran_log/releases/tag/v0.6.0) is what we said when we introduced the usage_cost model.
![image](https://github.com/user-attachments/assets/58588f47-23e6-43e8-a2fc-7a1ad68106b9)

Can we update this entry to be a bit more concise and straight forward.

2025-01-21 23:28 UTC, fivetran-jamie commented on models/staging/stg_fivetran_platform__transformation_runs.sql
> +    {% endif %}
Ah that's a great point! I think we should, as we've learned that Redshift won't respect the data type casts otherwise. @fivetran-reneeli can you add a condition to `limit 1` instead of 0 for Redshift targets

2025-01-22 16:03 UTC, fivetran-reneeli commented on CHANGELOG.md
> +    - We have also added the `get_transformation_runs_columns()` macro to ensure all required columns are present.
updated some of the language in the CHANGELOG

2025-01-22 16:03 UTC, fivetran-reneeli commented on CHANGELOG.md
> +- Added information about manually configuring the `fivetran_platform_using_transformations` variable in the [DECISION LOG.](https://github.com/fivetran/dbt_fivetran_log/blob/main/DECISIONLOG.md)## D
thanks for catching! removed

2025-01-22 17:11 UTC, fivetran-reneeli commented on CHANGELOG.md
> +  - If you would like to override these updates, you can also manually disable the `fivetran_platform_using_transformations` variable by setting it to False in your project.yml
Right it will be null if disabled. You're saying that it would be more likely that a customer disabling the variable would expect the fields not to be present at all, rather than null? The reason I did it this way was to mirror what is done for usage_cost, where if that table doesn't exist or is disabled, its downstream fields are all null. 

`fivetran_platform__usage_pricing: False`

![image](https://github.com/user-attachments/assets/2c9732e7-c67c-42d7-81c7-8a0ce89e637c)

2025-01-22 17:23 UTC, fivetran-reneeli commented on models/staging/stg_fivetran_platform__transformation_runs.sql
> +    {% endif %}
Yes! I believe I'll need to add it to [usage_cost ](https://github.com/fivetran/dbt_fivetran_log/blob/4ebb0e6d4c1af92960e06c4283323df38d362c85/models/staging/stg_fivetran_platform__usage_cost.sql#L33) and [credits_used](https://github.com/fivetran/dbt_fivetran_log/blob/4ebb0e6d4c1af92960e06c4283323df38d362c85/models/staging/stg_fivetran_platform__credits_used.sql#L33) as well though. I'll add that in and note it in the CHANGELOG.

2025-01-22 19:01 UTC, fivetran-reneeli commented on CHANGELOG.md
> +  - If you would like to override these updates, you can also manually disable the `fivetran_platform_using_transformations` variable by setting it to False in your project.yml
Updated the language to make it clearer that the fields will still be present but null.

2025-01-22 20:58 UTC, fivetran-joemarkiewicz approved these changes
Two updates before release. Once those are updated this will be good to go!

2025-01-22 20:58 UTC, fivetran-joemarkiewicz commented on CHANGELOG.md
> +- In addition, the following fields to the [`fivetran_platform__usage_mar_destination_history`](https://fivetran.github.io/dbt_fivetran_log/#!/model/model.fivetran_log.fivetran_platform__usage_mar_de
```suggestion
- In addition, the following fields have been added to the [`fivetran_platform__usage_mar_destination_history`](https://fivetran.github.io/dbt_fivetran_log/#!/model/model.fivetran_log.fivetran_platform__usage_mar_destination_history) end model:
```

2025-01-22 20:58 UTC, fivetran-joemarkiewicz commented on models/staging/src_fivetran_platform.yml
> +        identifier: "{{ var('fivetran_log_transformation_runs_identifier', 'transformation_runs') }}"
Looks like we are using the old name here. We need to update this to platform.
```suggestion
        identifier: "{{ var('fivetran_platform_transformation_runs_identifier', 'transformation_runs') }}"
```

2025-01-22 21:00 UTC, fivetran-joemarkiewicz commented on models/staging/src_fivetran_platform.yml
> +        identifier: "{{ var('fivetran_log_transformation_runs_identifier', 'transformation_runs') }}"
We reference the platform name in the platform named version [here](https://github.com/fivetran/dbt_fivetran_log/blob/9f095e8939740dfe8cab0e6084aef5cc1736cbbb/integration_tests/dbt_project.yml#L23) as well, so this will be consistent

2025-01-22 21:56 UTC, fivetran-jamie commented on models/fivetran_platform__usage_mar_destination_history.sql
> +        sum(case when free_type != 'PAID' then model_runs else 0 end) as free_model_runs,
Hey I saw this was added but don't we do `upper(free_type) as free_type` in the staging model?

2025-01-22 22:04 UTC, fivetran-reneeli commented on models/fivetran_platform__usage_mar_destination_history.sql
> +        sum(case when free_type != 'PAID' then model_runs else 0 end) as free_model_runs,
Oh you are 100% correct thanks for noticing that. I think it makes more sense to keep casing in staging, but I just realized everywhere else we do a lower albet in the transforms. I'll do a `lower` in the staging and remove it from the transforms. 

cc @fivetran-joemarkiewicz

2025-01-22 23:13 UTC, merged